from routers.courses import course_router
from routers.faculties import faculty_router
from routers.students import student_router
from routers.authentication import authentication_router
from routers.parents import parent_router
from routers.student_detail import student_detail_router
from routers.worked_place import worked_place_router
from routers.detail import detail_router
from routers.third_detail import third_detail_router